language: cpp
compiler:
  - gcc
  - clang
before_script:
 - sudo apt-get update
 - sudo apt-get install libboost-test-dev libz-dev 
 - wget http://ds9a.nl/antonie/test-files.tar.bz2
 - tar xf test-files.tar.bz2
script:
 - make -j 4
 - make -j 4 check
 - ./testrun.sh
notifications:
  email:
    - bert.hubert@netherlabs.nl

