#!/bin/sh
(echo -n \#define GIT_HASH \" ; git describe --always --dirty=+ | tr -d '\n' ; echo "\" ") > gitversion.h.tmp

cmp -s gitversion.h gitversion.h.tmp > /dev/null

if [ "$?" -ne "0" ]
then
	mv gitversion.h.tmp gitversion.h
	echo updated gitversion.h
	(echo -n \#; date) >  remake-please
else
	rm gitversion.h.tmp
fi


